name: apula
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.2.0
  lottie: ^3.1.2
  mobile_scanner: ^6.0.2
  audioplayers: ^6.0.0
  camera: ^0.10.5+2
  camera_web: ^0.3.3
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  device_info_plus: ^12.2.0
  geocoding: ^2.1.0
  geolocator: ^10.1.0

  # ‚≠ê MAP PACKAGES
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/apula-icon.png"

flutter:
  assets:
    - assets/logo.png
    - assets/check orange.json
    - assets/fireloading.json
    - assets/apula-icon.png
    - assets/apula_home_icon.png
    - assets/sounds/fire_alarm.mp3
    - assets/examples/fire_example.jpg
    - assets/examples/profile_pic.jpg
    - assets/examples/thermal_example.png
  uses-material-design: true
