name: apula
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"   # ✔ CORRECT for Flutter 3.19.6

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0

  # UI
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  provider: ^6.1.2

  # Device / permissions
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0

  # Camera
  camera: ^0.11.0
  camera_web: ^0.3.5+1

  # Audio
  audioplayers: ^6.0.0

  # Geolocation + map
  geocoding: ^2.2.1
  geolocator: ^11.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

  # Auth & scanner
  local_auth: ^2.2.0
  mobile_scanner: ^6.0.2

  # Firebase — COMPATIBLE WITH FLUTTER 3.19 / DART 3.3+
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  firebase_database: ^10.5.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.3

  #video player for demo
  video_player: ^2.8.2

  # ML (compatible)
  tflite_flutter: ^0.12.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/apula-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/check orange.json
    - assets/fireloading.json
    - assets/apula-icon.png
    - assets/apula_home_icon.png
    - assets/sounds/fire_alarm.mp3
    - assets/examples/fire_example.jpg
    - assets/examples/profile_pic.jpg
    - assets/examples/thermal_example.png
    - assets/models/APULA_FUSION_CNN_v2.tflite
    - assets/models/feature_scaler.json
    - assets/ml/cnn_model_quant.tflite
    - assets/ml/cnn_scaler.json
